<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.4.6</Version>
    <AssemblyTitle>FishShop</AssemblyTitle>
    <Product>FishShop</Product>
    <Copyright>Copyright © hufang360 2022</Copyright>
    <!-- extras for nuget -->
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Authors>hufang360</Authors>
    <Description>指令商店，支持使用金币和物品来购买 物品、召唤boss、生成NPC、获得buff、调时间 等。</Description>
    <PackageId>FishShop</PackageId>
    <AssemblyName>FishShop</AssemblyName>
  </PropertyGroup>
    
  <ItemGroup>
    <None Remove="res\config.json" />
    <None Remove="res\settings.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="res\config.json" />
    <EmbeddedResource Include="res\settings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UnrealMultiple.TShock-Beta" Version="6.0.1" />
  </ItemGroup>

</Project>
